version: "3.4"

services:
  localstack:
    image: localstack/localstack:0.13.1
    ports:
      - "4566:4566"
      - "4571:4571"
      # - '8080:8080' # the localstack admin portal
    container_name: localstack
    environment:
      - SERVICES=lambda,s3
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_USE_SSL=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock

# Allows to save data in the host of the container
volumes:
  rigacron:
    driver: local
