service: riga-cron

# MIO: Commented out the framework to use `serverless plugin install -n serverless-python-requirements`
# frameworkVersion: '2 || 3'

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function
  # bundles requirements when you run sls deploy: https://www.serverless.com/plugins/serverless-python-requirements
  #    https://www.npmjs.com/package/serverless-python-requirements
  - serverless-python-requirements
  - serverless-prune-plugin
  # Specify in .slsignore files ignored by serverless: https://www.serverless.com/plugins/serverless-ignore
  - serverless-ignore

# Reference for parameters in serverless.yml
# https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml

provider:
  name: aws
  runtime: python3.8

functions:
  cronDownloader:
    handler: src/functions/cron-downloader.run
    events: 
      - http:
          method: get
          path: download
    layers:
      - Ref: PythonRequirementsLambdaLayer          
    iamRoleStatementsName: riga-cron-downloader-role
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:listBucket
        Resource: ${self:custom.infrastructureCronS3BucketArn}
      - Effect: "Allow"
        Action:
          - s3:getObject
          - s3:putObject
        Resource: ${self:custom.infrastructureCronS3BucketArn}/*

    # events:
    #   # NOTE: Times depend on AWS region deployed - should be same as NYSE
    #   # Every 3 minutes, between 10:00 PM and 08:00 AM, Monday through Friday
    #   - schedule: cron(0/3 22-08 * * MON-FRI *)

custom:
  stage: ${opt:stage, 'local'}
  filename: ./config/serverless.${self:custom.stage}.config.yml
  env: ${opt:env, 'local'}
  infrastructureCronS3BucketArn: ${file(${self:custom.filename}):infrastructure_cronS3BucketArn,''}
  # Reserve a maximum number of concurrent instances (default: account limit)
  reservedConcurrency: 5
  pythonRequirements:
    # zip: true
    layer: true
    slim: true
  prune:
    automatic: true
    number: 3
