service: riga-cron

# MIO: Commented out the framework to use `serverless plugin install -n serverless-python-requirements`
# frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  cronHandler:
    handler: scr/functions/handler.run
    # events:
    #   # Invoke function (US region times): Every 3 minutes, between 07:00 PM and 08:59 AM, Monday through Friday
    #   - schedule: cron(0/3 22-13 * * MON-FRI *)

plugins:
  - serverless-python-requirements
