service: riga-cron

# MIO: Commented out the framework to use `serverless plugin install -n serverless-python-requirements`
# frameworkVersion: '2 || 3'

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-python-requirements
  - serverless-prune-plugin

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  cronDownloader:
    handler: src/functions/cron-downloader.run
    events:
      - http:
          method: get
          path: download
    iamRoleStatementsName: riga-cron-downloader-role
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:putObject
        Resource: ${self:custom.infrastructureCronS3BucketArn}/*

    # events:
    #   # Invoke function (US region times): Every 3 minutes, between 07:00 PM and 08:59 AM, Monday through Friday
    #   - schedule: cron(0/3 22-13 * * MON-FRI *)
