version: "3.8"
services:
  rigacron:
    build:
      # Where is the Dockerfile relative to the compose file. This directory is also the build context sent to the Docker daemon.
      # https://stackoverflow.com/questions/65622477/what-is-context-in-docker-compose
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    init: true
    volumes:
      # Map data folder to local folder
      - ../:/usr/src
      # Named volume to persist node_modules
      - node-modules:/root/.node-modules
      # Persist VS Code extensions between rebuilds
      - vscode-extensions:/root/.vscode-server/extensions

    container_name: riga-cron-development
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

volumes:
  node-modules:
  vscode-extensions:
