version: "3.8"
services:
  rigacron:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    init: true
    volumes:
      # Use a named volume for the source code
      - riga-cron:/usr/src
      # Persist VS Code extensions between rebuilds
      - vscode-extensions:/root/.vscode-server/extensions

    container_name: riga-cron-development
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

volumes:
  riga-cron:
  vscode-extensions: