version: "3.8"
services:
  rigacron:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    init: true
    volumes:
      # Map data folder to local folder
      - ./:/usr/src
      # Use a named volume for the source code (app code, node_modules...)
      # - node-modules:/root/.node-modules
      # Persist VS Code extensions between rebuilds
      - vscode-extensions:/root/.vscode-server/extensions

    container_name: riga-cron-development
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

volumes:
  rigacron:
    driver: local
  app:
  vscode-extensions:
